- fixed colon in password bug

diff --git a/cgi-bin/afswrapper b/cgi-bin/afswrapper
--- a/cgi-bin/afswrapper
+++ b/cgi-bin/afswrapper
@@ -40,7 +40,7 @@ if test -n "$AUTHHEADER" ; then
 	if test ! -f "$ticketfn" ; then
 		(
 			flock -x -w 10 9 || exit 1
-			echo $AUTHHEADER | cut -d' ' -f2 | base64 -d | cut -d: -f2 | kinit "$remote_user" 1>/dev/null 2>&1 || error "500 (kinit)"
+			echo $AUTHHEADER | cut -d' ' -f2 | base64 -d | sed -re 's@^[^:]+:@@' | kinit "$remote_user" 1>/dev/null 2>&1 || error "500 (kinit)"
 		) 9> "${ticketfn}.flock" || exit 1
 	fi
 fi
